# Generated by Django 3.1.5 on 2021-02-14 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('home', '0003_auto_20210110_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='test_text',
            field=models.TextField(default=1, help_text='Nur ein Test Text', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='homepage',
            name='banner_hintergrund_bild',
            field=models.ForeignKey(help_text='Banner Hintergrundbild', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_text',
            field=models.TextField(help_text='Text neben/unter dem Banner', max_length=500),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_titel',
            field=models.CharField(help_text='Überschrift erster Abschnitt', max_length=140),
        ),
    ]
