# Generated by Django 3.1.5 on 2021-02-14 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0059_apply_collection_ordering'),
        ('home', '0005_remove_homepage_test_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='bild_link',
            field=models.ForeignKey(blank=True, help_text='Link für das Hintergrundbild hinterlegen', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
    ]
