# Generated by Django 3.1.5 on 2021-02-14 07:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0059_apply_collection_ordering'),
        ('wagtailimages', '0022_uploadedimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('home', '0006_homepage_bild_link'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomePage',
            new_name='Hero',
        ),
    ]
