# Generated by Django 3.1.5 on 2021-02-14 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0059_apply_collection_ordering'),
        ('home', '0008_auto_20210214_0838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seitemitherobanner',
            name='bild_link',
        ),
        migrations.AddField(
            model_name='seitemitherobanner',
            name='bild_link_extern',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='seitemitherobanner',
            name='bild_link_intern',
            field=models.ForeignKey(blank=True, help_text='Interner Link für das Hintergrundbild hinterlegen', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
    ]
