# Generated by Django 3.1.5 on 2021-02-14 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210214_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seitemitherobanner',
            name='bild_link_extern',
            field=models.URLField(blank=True, help_text='Verlinkung zu einer externen Seite'),
        ),
        migrations.AlterField(
            model_name='seitemitherobanner',
            name='hero_text',
            field=models.TextField(help_text='Text neben/unter dem Banner. Maximal 500 Zeichen.', max_length=500),
        ),
    ]
