# Generated by Django 3.1.5 on 2021-02-14 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20210214_1139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seitemitherobanner',
            options={'verbose_name': 'Hero Banner'},
        ),
    ]
