# Generated by Django 3.1.5 on 2021-02-14 17:34

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20210214_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='seitemitherobanner',
            name='body',
            field=wagtail.core.fields.StreamField([('titel', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.CharBlock(help_text='Anzeigetext', required=True))]))], blank=True, null=True),
        ),
    ]
