# Generated by Django 3.1.5 on 2021-02-14 18:26

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_seitemitherobanner_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seitemitherobanner',
            name='body',
            field=wagtail.core.fields.StreamField([('titel', wagtail.core.blocks.StructBlock([('Titel', wagtail.core.blocks.CharBlock(required=True))]))], blank=True, null=True),
        ),
    ]
