# Generated by Django 3.1.5 on 2021-02-14 20:14

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20210214_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seitemitherobanner',
            name='body',
            field=wagtail.core.fields.StreamField([('titel', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.CharBlock(required=True))])), ('cards', wagtail.core.blocks.StructBlock([('cards', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('titel', wagtail.core.blocks.CharBlock(help_text='Fett formatierter Text. Maximale Länge 100 Zeichen', max_length=100)), ('text', wagtail.core.blocks.TextBlock(help_text='Optionaler Text. Maximale Länge 255 Zeichen', max_length=255, required=False)), ('bild', wagtail.images.blocks.ImageChooserBlock(help_text='Bild in der Größe 570px x 370px'))])))]))], blank=True, null=True),
        ),
    ]
