# Generated by Django 3.1.5 on 2021-02-15 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailcore', '0059_apply_collection_ordering'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('flex', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FlexibleSeite',
        ),
    ]
